"""empty message

Revision ID: 722168d15827
Revises: 157c44a421f5
Create Date: 2021-03-28 23:05:31.042978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '722168d15827'
down_revision = '157c44a421f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('meals')
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.create_table('meals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pickup_start_time', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pickup_end_time', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('max_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='meals_pkey')
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chef_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('item_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('picture_url', sa.VARCHAR(length=600), autoincrement=False, nullable=True),
    sa.Column('portion_size', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    # ### end Alembic commands ###
