"""empty message

Revision ID: 990076f6ad5e
Revises: 44b636908471
Create Date: 2021-03-18 19:06:16.320373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990076f6ad5e'
down_revision = '44b636908471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.create_unique_constraint(None, 'chefs', ['user_id'])
    op.add_column('users', sa.Column('profile_pic_url', sa.String(length=400), nullable=True))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'profile_pic_url')
    op.drop_constraint(None, 'chefs', type_='unique')
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('dealer', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='feedback_pkey'),
    sa.UniqueConstraint('customer', name='feedback_customer_key')
    )
    # ### end Alembic commands ###
